name: Hello World PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = context.payload.comment.body;
            const isPR = context.payload.issue.pull_request != null;

            if (isPR && comment.includes('/hello')) {
              console.log('Hello, world!');
            }
